### ISSUE TITLE
No iso

### ISSUE THREAD

**Issue by tree-t** [wooter6928196219911/rickos#1]
Hey @wooter6928196219911,
I know that rickos is in an alpha state(as it doesn't boot), but could you please add an iso for this os, as I am interested and wish to help you with it.( Previously I have tried to answer your issue issue at 
[Could not locate rick os data](https://github.com/tomas-m/linux-live/issues/185) 
But I received no response from you, hence I am writing this to you as an issue).

**Comment by tree-t** [comment]
But you said that you won't give up!

**Comment by wooter6928196219911** [comment]
I will probably make the iso when I feel like because i lost it over formatting my computer for the 500th time and i will build my own scripts for it.

**Comment by tree-t** [comment]
Ok
